### ISSUE TITLE
When pip-installing, the `relic` package wasn't found.

### ISSUE THREAD

**Issue by wmwv** [spacetelescope/pysynphot#83]
When installing using `pip`, the `relic` package wasn't found.  Python 3.6.3, Mac OS X 10.13.3.

When I separately pip-installed `relic` and then pip-installed `pysynphot`, it worked fine.  Perhaps something in the submodule isn't getting seen correctly in the pip install.

```
[serenity ~] pip3 install pysynphot
Collecting pysynphot
  Downloading pysynphot-0.9.9.tar.gz (8.8MB)
    100% |████████████████████████████████| 8.8MB 181kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cr/6mtr09kc8xj40b0059b98ffh0000gn/T/pip-build-ox8e8mq8/pysynphot/setup.py", line 9, in <module>
        import relic.release  # noqa
    ModuleNotFoundError: No module named 'relic'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cr/6mtr09kc8xj40b0059b98ffh0000gn/T/pip-build-ox8e8mq8/pysynphot/
```

```
[serenity ~] pip3 install relic
Collecting relic
  Downloading relic-1.0.6.tar.gz
Building wheels for collected packages: relic
  Running setup.py bdist_wheel for relic ... done
  Stored in directory: /Users/wmwv/Library/Caches/pip/wheels/49/4b/cd/505e9f2f0b42afb8319b066fe076d10a283a1424a042f14339
Successfully built relic
Installing collected packages: relic
Successfully installed relic-1.0.6
[serenity ~] pip3 install pysynphot
Collecting pysynphot
  Using cached pysynphot-0.9.9.tar.gz
Requirement already satisfied: astropy in /usr/local/lib/python3.6/site-packages/astropy-3.1.dev21342-py3.6-macosx-10.12-x86_64.egg (from pysynphot)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/site-packages (from pysynphot)
Building wheels for collected packages: pysynphot
  Running setup.py bdist_wheel for pysynphot ... done
  Stored in directory: /Users/wmwv/Library/Caches/pip/wheels/ab/90/20/1ad18ffb7e4814d116c34a4c513c116e3b2de1add1e28eca0e
Successfully built pysynphot
Installing collected packages: pysynphot
Successfully installed pysynphot-0.9.9
```

**Comment by pllim** [comment]
Note to self: Close this after *next* release (TBD).

**Comment by pllim** [comment]
Should be in 0.9.10 released today.
